### ISSUE TITLE
'Math' Name change suggestion

### ISSUE THREAD

**Issue by SpunkyMaXimz** [znjameswu/flutter_math#16]
This is just a suggestion, you can ignore it for any reason. The class name `Math`, when I think of, resembles Math.java or similar math libraries and I would prefer using something like `Texxt()` or `TeXt()` instead of `Math.tex()`.

But again, just a suggestion. 
Thanks.

**Comment by znjameswu** [comment]
Thank you for the suggestion. In fact this was a part of the discussion during the most recent 0.2.0 API changes. https://github.com/znjameswu/flutter_math/issues/10

The reason I didn't go for something like `TeX` is that this project is not intended to be coupled with TeX since the beginning. I intend to bring UnicodeMath editing support in the future, so TeX is only one of the accepted input formats. 

You are more than welcome to bring up better names, because the current name is admittedly controversial even in the original discussions.

**Comment by SpunkyMaXimz** [comment]
oh, that is the reason behind .tex() constructor. ok, I got your point.
And since the #10 talks about it, I am closing this 😅.
